apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: darkdevil086/devops-app:latest
        ports:
        - containerPort: 5000

apiVersion: v1
kind: Pod
metadata:
  name: devops-app-pod
  labels:
    app: devops-app
spec:
  containers:
  - name: devops-app-container
    image: darkdevil/devops-app
    ports:
      - containerPort: 5000